prompt = """
You can organize your source of truth arbitrarily if you are using an 
unstructured source of truth. If you are using a hierarchical source of truth, 
you need to run the `nomos init` command to initialize a hierarchical directory.

This creates the basic directory structure of a hierarchical source of truth, 
including the `system/`, `cluster/`, and `namespaces/` directories.

Usage:
!{nomos init}
"""
