prompt = """
You can monitor the status of Config Sync on all enrolled clusters by using the `nomos status` command. For each cluster, `nomos status` reports 
the hash of the commit that was last applied to the cluster and any errors that occurred while trying to apply any recent changes.

You can also use `nomos status` to check if the resources managed by Config Sync are ready. `nomos status` reports the status for each 
individual resource in the `STATUS` column of the `Managed resources` section of the output.

Usage:
!{nomos status}
"""
